### ISSUE TITLE
Rails 5.0.0.beta4

### ISSUE THREAD

**Issue by spickermann** [railsdiff/api#3]
It seems like Rails 5.0.0.beta4 was added to the API a few days ago, but it still doesn't show up on http://railsdiff.org/. Does the change need to be deployed?

**Comment by neumayr** [comment]
http://api.railsdiff.org/versions

didn't include `5.0.0.beta4` in it's response

**Comment by spickermann** [comment]
@neumayr That's exactly the question: Why isn't it included in the API, although it was added in this commit: https://github.com/railsdiff/api/commit/61a502ac49777e2b3a98541b64cb12d31db784a7?
